---
- name: Install clipster
  aur:
    name: clipster

- name: Make sure config directory exists
  file:
    path: "{{ config_home }}/clipster"
    state: directory

- name: Configure clipster
  ini_file:
    path: "{{ config_home }}/clipster/clipster.ini"
    section: clipster
    option: default_selection
    value: CLIPBOARD

- name: Configure clipster service file
  template:
    src: clipster.service.j2
    dest: '{{ config_home }}/systemd/user/clipster.service'

- name: Enable clipster service
  file:
    src: '{{ config_home }}/systemd/user/clipster.service'
    dest: '{{ config_home }}/systemd/user/default.target.wants/clipster.service'
    state: link
