---
- name: Install clipster
  aur:
    name: clipster

- name: Configure clipster service file
  template:
    src: clipster.service.j2
    dest: '{{ config_home }}/systemd/user/clipster.service'

- name: Enable clipster service
  file:
    src: '{{ config_home }}/systemd/user/clipster.service'
    dest: '{{ config_home }}/systemd/user/default.target.wants/clipster.service'
    state: link
