---
- name: Install clipster
  pacman:
    name: clipster
  become: true

- name: Configure clipster service file
  template:
    src: clipster.service.j2
    dest: '{{ defaults.config_home }}/systemd/user/clipster.service'

- name: Enable and start clipster service
  systemd:
    name: clipster
    daemon-reload: yes
    user: yes
    enabled: yes
    state: started
