---
- name: Install VLC
  pacman:
    name: vlc
  become_user: root

- name: Install optional dependencies
  pacman:
    name: '{{ item }}'
  become_user: root
  loop:
    - protobuf
    - libmicrodns
