---
- name: Install Firefox
  pacman:
    name: firefox
  become: true

- name: Configure profiles
  template:
    src: profiles.ini.j2
    dest: '{{ ansible_user_dir }}/.mozilla/firefox/profiles.ini'

- name: Configure Firefox's GUI
  copy:
    src: userChrome.css
    dest: '{{ ansible_user_dir }}/.mozilla/firefox/{{ profile_dir }}.default/chrome/'

# Manual steps to get back Firefox as I want it:
#  - import vimium configs (in files/vimium) through the interface
#  - import userstyles (in files/userstyles.bin) through their interface
#  - change Tab Session Manager's settings
#    - Uncheck 'Save the session regularly'
#    - Change Date format to DD/MM/YYYY HH:mm:ss
#  - Customize GUI
#  - Make DuckDuckGo the default search engine at 'about:preferences#search'
#  - Block requests to allow notifications at 'about:preferences#privacey' -> Permissions -> Notifications
