---
- name: Install redshift
  aur:
    name: redshift-wlr-gamma-control-git

- name: Create configuration directory
  file:
    path: '{{ config_home }}/redshift'
    state: directory

- name: Configure redshift
  template:
    src: redshift.conf.j2
    dest: '{{ config_home }}/redshift/redshift.conf'

- name: Configure redshift service file
  template:
    src: redshift.service.j2
    dest: '{{ config_home }}/systemd/user/redshift.service'

- name: Enable redshift service
  file:
    src: '{{ config_home }}/systemd/user/redshift.service'
    dest: '{{ config_home }}/systemd/user/default.target.wants/redshift.service'
    state: link
