---
- name: Install fish
  pacman:
    name: fish
  become_user: root

- name: Create fish config directory
  file:
    path: '{{ config_home }}/fish'
    state: directory

- name: Copy all files
  copy:
    src: ./
    dest: '{{ config_home }}/fish/'

- import_tasks: universals.yml

- import_tasks: fisherman.yml
