---
- name: Configure theme parameters
  lineinfile:
    path: '{{ defaults.config_home }}/fish/fishd.{{ ansible_hostname }}'
    regexp: '^SET theme_{{ item.key }}:'
    line: 'SET theme_{{ item.key }}:{{ item.value|fishd_escape }}'
    create: yes
  with_dict:
    display_git: 'yes'
    display_git_dirty: 'yes'
    display_git_untracked: 'yes'
    display_docker_machine: 'yes'
    display_virtualenv: 'yes'
    display_vi: 'yes'
    display_date: 'no'
    avoid_ambiguous_glyphs: 'no'
    powerline_fonts: 'yes'
    nerd_fonts: 'yes'
    color_scheme: gruvbox
    newline_cursor: 'no'


- name: Configure colors
  lineinfile:
    path: '{{ defaults.config_home }}/fish/fishd.{{ ansible_hostname }}'
    regexp: '^SET fish_color_{{ item.key }}:'
    line: "SET fish_color_{{ item.key }}:{{ item.value|fishd_escape|replace('\\x20', '\\x1e') }}"
    create: yes
  with_dict:
    autosuggestion: "brblack --italics --dim"
    command: "white --bold"
    comment: "brblack"
    end: "brgreen --bold"
    error: "brred"
    param: "brblue"
    quote: "bryellow --italics"
    redirection: "brmagenta --bold"


- name: Configure other parameters
  lineinfile:
    path: '{{ defaults.config_home }}/fish/fishd.{{ ansible_hostname }}'
    regexp: '^SET {{ item.key }}:'
    line: 'SET {{ item.key }}:{{ item.value|fishd_escape }}'
    create: yes
  with_dict:
    fish_key_bindings: fish_vi_key_bindings
    VIRTUAL_ENV_DISABLE_PROMPT: 1

- name: Get abbreviations from file
  shell: >
    cat {{ role_path }}/files/abbreviations |
    sed -e '/^$/d' -e '/^#/d' |
    awk '{print}' ORS='\x1e' |
    sed 's/.$//'
  register: print_abbreviations
  changed_when: False

- name: Configure abbreviations
  lineinfile:
    path: '{{ defaults.config_home }}/fish/fishd.{{ ansible_hostname }}'
    regexp: '^SET fish_user_abbreviations:'
    line: 'SET fish_user_abbreviations:{{ item|fishd_escape }}'
    create: yes
  with_items: '{{ print_abbreviations.stdout }}'
