---
- name: Configure universal variables
  command: set -U "{{ item.key }}" "{{ item.value }}"
  with_dict:
    # fish colors
    autosuggestion: "brblack --italics --dim"
    command: "white --bold"
    comment: "brblack"
    end: "brgreen --bold"
    error: "brred"
    param: "brblue"
    quote: "bryellow --italics"
    redirection: "brmagenta --bold"
    # config
    fish_key_bindings: fish_vi_key_bindings

- name: Configure abbreviations
  command: abbr "{{ item.key }}" "{{ item.value }}"
  with_dict: '{{ abbreviations }}'
