---
- name: clone {{ item }} AUR repository
  git:
    repo: https://aur.archlinux.org/{{ item }}.git
    dest: /tmp/{{ item }}
    version: master
  loop:
    - package-query
    - yaourt

- name: install {{ item }}
  command: makepkg -sirc --noconfirm PKGBUILD
  args:
    chdir: /tmp/{{ item }}
  register: '{{ item }}_install'
  loop:
    - package-query
    - yaourt

- debug:
  var: '{{ item }}_install.stderr'
  loop:
    - package-query
    - yaourt

- name: remove {{ item }} directory
  file:
    path: /tmp/{{ item }}
    state: absent
  loop:
    - package-query
    - yaourt
