---
- name: Check if yaourt is installed
  command: pacman -Q yaourt
  register: installed
  changed_when: False
  ignore_errors: True

- include_tasks: install.yml
  when: installed is failed

- name: Create yaourt config directory
  file:
    path: '{{ defaults.config_home }}/yaourt'
    state: directory

- name: Configure yaourt
  template:
    src: yaourtrc.j2
    dest: '{{ defaults.config_home }}/yaourt/yaourtrc'
