---
- name: Check if yaourt is installed
  command: pacman -Q yaourt
  register: yaourt_installed
  changed_when: false
  ignore_errors: true

- import_tasks: install.yml
  when: yaourt_installed is failed

- name: Create yaourt config directory
  file:
    path: '{{ config_home }}/yaourt'
    state: directory

- name: Configure yaourt
  template:
    src: yaourtrc.j2
    dest: '{{ config_home }}/yaourt/yaourtrc'
