---
- block:
    - name: Check if yaourt is installed
      command: pacman -Q yaourt
      changed_when: false
  rescue:
    - name: Temporarly add the 'archlinuxfr' repo to pacman.conf 
      blockinfile:
        path: /etc/pacman.conf
        block: |
          [archlinuxfr]
          SigLevel = Never
          Server = http://repo.archlinux.fr/$arch
      become_user: root

    - name: Install yaourt
      pacman:
        name: yaourt
        update_cache: yes
      become_user: root

    - name: Remove the 'archlinuxfr' repo from pacman.conf
      blockinfile:
        path: /etc/pacman.conf
        state: absent
        block: |
          [archlinuxfr]
          SigLevel = Never
          Server = http://repo.archlinux.fr/$arch
      become_user: root

- name: Create yaourt config directory
  file:
    path: '{{ config_home }}/yaourt'
    state: directory

- name: Configure yaourt
  template:
    src: yaourtrc.j2
    dest: '{{ config_home }}/yaourt/yaourtrc'
