---
- name: Install CUPS
  pacman:
    name: '{{ item }}'
  loop:
    - cups
    - cups-pdf
  become_user: root

- name: Enable the services/sockets
  systemd:
    name: '{{ item }}'
    enabled: yes
  loop:
    - avahi-daemon.socket
    - org.cups.cupsd
  become_user: root
