---
- name: Configure hostname
  template:
    src: hostname.j2
    dest: /etc/hostname
  become_user: root

- name: Configure hosts file
  template:
    src: hosts.j2
    dest: /etc/hosts
  become_user: root
