---
- hosts: localhost
  vars_prompt:
    - name: disk
      prompt: 'Which disk do you want to install arch on? (ex: sda)'
    - name: wipe_disk
      prompt: Do you want to wipe the disk? (yes/NO)
      default: no
    - name: encrypt_root
      prompt: Do you want to encrypt the root partition? (yes/no)
    - name: fstype
      prompt: 'What filesystem do you want your root paritition do be formated with? (ex: ext4)'
  vars:
    - is_efi: '{{ "/sys/firmware/efi" is exists }}'
    - is_ssd: '{{ ansible_devices[disk].rotational == 0 }}'
    - is_nvme: '{{ "nvme" in disk }}'
    - is_intel_cpu: '{{ l("pipe",
      "lscpu | grep "Vendor ID" | cut -d: -f2 | tr -d "[:blank:]") == "GenuineIntel" }}'
    - boot_partition: '{{ disk + "1" if not is_nvme else "p1" }}'
    - root_partition: '{{ disk + "2" if not is_nvme else "p2" }}'
    - encrypted_root: '{{ l("pipe", "cryptsetup isLuks " + root_partition) is succeeded }}'

  pre_tasks:
  - name: Enable and start NTP
    systemd:
      name: systemd-timesyncd
      enabled: yes
      state: started

  roles:
    # BE CAREFUL, THIS ROLE IS NOT IDEMPOTENT
    - role: wipe
      tags: wipe
      when: wipe_disk

    - role: partition
      tags: partition

    - role: encrypt
      tags: encrypt
      when: encrypt_disk

    - role: format
      tags: format

    - role: arch-install
      tags: arch-install
