---
- hosts: localhost
  vars_prompt:
    - name: disk
      prompt: Which disk do you want to install arch on? (e.g. sda)
      private: no
    - name: wipe_disk
      prompt: Do you want to wipe the disk? (yes/NO)
      default: no
      private: no
    - name: encrypt_root
      prompt: Do you want to encrypt the root partition? (yes/no)
      private: no
    - name: fstype
      prompt: What filesystem do you want your root paritition do be formated with? (e.g. ext4)
      private: no
  pre_tasks:
  - name: Enable and start NTP
    systemd:
      name: systemd-timesyncd
      enabled: yes
      state: started

  post_tasks:
  - name: Mount /proc, /sys, /dev and /run to /mnt
    mount:
      src: /{{ item.dir }}
      path: /mnt/{{ item.dir }}
      fstype: '{{ item.fstype }}'
      opts: '{{ item.option|default(omit) }}'
      state: mounted
    loop:
      - { dir: proc, fstype: proc }
      - { dir: sys, fstype: none, option: bind }
      - { dir: dev, fstype: none, option: bind }
      - { dir: run, fstype: none, option: bind }

  - name: Copy 'resolv.conf'
    copy:
      src: /etc/resolv.conf
      dest: /mnt/etc/resolv.conf

  roles:
    # BE CAREFUL, THIS ROLE IS NOT IDEMPOTENT
    - role: wipe
      tags: wipe
      when: wipe_disk|bool

    - role: partition
      tags: partition

    - role: encrypt
      tags: encrypt
      when: encrypt_root|bool

    - role: format
      tags: format

    - role: arch-install
      tags: arch-install

- name: Install setup
  import_playbook: site.yml 
  vars:
    hostlist: all
    connection_type: chroot

- hosts: localhost
  tasks:
  - name: Unmount '/mnt/{{ item }}'
    mount:
      path: /mnt/{{ item }}
      state: unmounted
    loop:
      - proc
      - sys
      - dev
