---
- hosts: localhost
  gather_facts: false
  pre_tasks:
    - name: Make sure time is correct
      command: timedatectl set-ntp true
      changed_when: false

    - name: Check if 'efi' directory exists
      block:
        - stat:
            path: /sys/firmware/efi
          register: efi

        - set_fact:
            is_efi: '{{ efi.stat.exists }}'

    - name: Check if '{{ disk }}' is a ssd
      block:
        - command: cat /sys/block/{{ disk }}/queue/rotational
          changed_when: false
          register: rotational

        - set_fact:
            is_ssd: '{{ rotational.stdout == 0 }}'

    - name: Set fact for whether SSD is NVMe
      set_fact:
        is_nvme: '{{ "nvme" in disk }}'

    - name: Check if it's an Intel CPU
      block:
        - shell: lscpu | grep 'Model name:'
          changed_when: false
          register: cpu

        - name: Set fact for whether it's an Intel CPU
          set_fact:
            is_intel_cpu: '{{ "Intel" in cpu.stdout }}'

  roles:
    - role: arch-install
