---
- hosts: localhost
  gather_facts: false
  pre_tasks:
    - name: Make sure time is correct
      command: timedatectl set-ntp true
      changed_when: false

    - name: Set fact for whether 'efi' directory exists
      set_fact:
        is_efi: '{{ "/sys/firmware/efi" is exists }}'

    - name: Set fact for whether '{{ disk }}' is an SSD
      set_fact:
        is_ssd: '{{ lookup("file", "/sys/block/{{ disk }}/queue/rotational") == "0" }}'

    - name: Set fact for whether SSD is NVMe
      set_fact:
        is_nvme: '{{ "nvme" in disk }}'

    - name: Check if it's an Intel CPU
      block:
        - shell: lscpu | grep 'Model name:'
          changed_when: false
          register: cpu

        - name: Set fact for whether it's an Intel CPU
          set_fact:
            is_intel_cpu: '{{ "Intel" in cpu.stdout }}'

  roles:
    - role: arch-install
