---
- hosts: localhost
  become: yes
  vars_prompt:
    - name: disk
      prompt: Which disk do you want to install arch on? (e.g. sda)
      private: no
    - name: wipe_disk
      prompt: Do you want to wipe the disk? (yes/NO)
      default: no
      private: no
    - name: encrypt_root
      prompt: Do you want to encrypt the root partition? (yes/no)
      private: no
    - name: fstype
      prompt: What filesystem do you want your root paritition do be formated with? (e.g. ext4)
      private: no
  vars:
  pre_tasks:
  - name: Enable and start NTP
    systemd:
      name: systemd-timesyncd
      enabled: yes
      state: started

  roles:
    # BE CAREFUL, THIS ROLE IS NOT IDEMPOTENT
    - role: wipe
      tags: wipe
      when: wipe_disk|bool

    - role: partition
      tags: partition

    - role: encrypt
      tags: encrypt
      when: encrypt_root|bool

    - role: format
      tags: format

    - role: arch-install
      tags: arch-install
