---
- hosts: localhost
  pre_tasks:
    - name: Query present graphics cards
      shell: lspci | grep -e VGA -e 3D
      register: present_gpus
      changed_when: false
      tags:
        - intel_graphics
        - nvidia
        - display

    - name: Set facts for GPUs
      set_fact:
        nvidia_gpu_present: "{{ 'nvidia' in present_gpus.stdout|lower }}"
        intel_gpu_present: "{{ 'intel' in present_gpus.stdout|lower }}"
      tags:
        - intel_graphics
        - nvidia
        - display

  tasks:
    - name: "Clone this repo to {{ ansible_user_id }}'s home"
      git:
        repo: git@github.com:Sweenu/setup.git
        dest: '{{ ansible_user_dir }}/setup'
        update: no

  roles:
    - role: timezone
      tags: [ timezone, install ]

    - role: locale
      tags: [ locale, install ]

    - role: hostname
      tags: [ hostname, install ]

    - role: mkinitcpio
      tags: [ mkinitcpio, install ]

    - role: python
      tags: [ python, install ]

    - role: pacman
      tags: [ pacman, install ]

    - role: grub
      tags: [ grub, install ]

    - role: users
      tags: [ users, install ]

    - role: linux_console
      tags: [ linux_console, install ]

    - role: sudoers
      tags: [ sudoers, install ]

    - role: time
      tags: time

    - role: networkmanager
      tags: networkmanager

    - role: ansible
      tags: ansible

    - role: logind
      tags: logind

    - role: ssh
      tags: ssh

    - role: git
      tags: git

    - role: yaourt
      tags: yaourt

    - role: systemd
      tags: systemd

    - role: gnome-keyring
      tags: gnome-keyring

    - role: fonts
      tags: fonts

    - role: profile
      tags: profile

    - role: xdg-user-dirs
      tags: xdg-user-dirs

    - role: xorg
      tags:
        - xorg
        - display

    - role: nvidia
      when: nvidia_gpu_present
      tags:
        - nvidia
        - display

    - role: intel_graphics
      when: intel_gpu_present
      tags:
        - intel_graphics
        - display

    - role: lightdm
      tags: lightdm

    - role: backlight
      tags: backlight

    - role: neovim
      tags: neovim

    - role: oni
      tags: oni

    - role: bluetooth
      tags: bluetooth

    - role: tlp
      tags: tlp
      when: ansible_form_factor == 'Laptop'

    - role: gtk3
      tags: gtk3

    - role: cups
      tags: cups

    - role: rclone
      tags: rclone

    - role: pulseaudio
      tags: pulseaudio

    - role: fish
      tags: fish

    - role: clipster
      tags: clipster

    - role: qtile
      tags: qtile

    - role: spotify
      tags: spotify

    - role: deepin-tools
      tags: deepin-tools

    - role: dunst
      tags: dunst

    - role: termite
      tags: termite

    # - role: tunnelbear
    #   tags: tunnelbear

    - role: kdeconnect
      tags: kdeconnect

    - role: ranger
      tags: ranger

    - role: redshift
      tags: redshift

    - role: vimiv
      tags: vimiv

    - role: taskwarrior
      tags: taskwarrior

    - role: docker
      tags: docker

    - role: firefox
      tags: firefox

    - role: glances
      tags: glances

    - role: light-locker
      tags: light-locker

    - role: alsi
      tags: alsi

    - role: ufw
      tags: ufw

    # - role: lutris
    #   tags: lutris

    - role: latex
      tags: latex

    - role: rofi
      tags: rofi

    - role: openlp
      tags: openlp

    - role: others
      tags: others
