---
- hosts: localhost
  roles:
    - role: time
      tags: time

    - role: locale
      tags: locale

    - role: console_keyboard_layout
      tags: console_keyboard_layout

    - role: hostname
      tags: hostname

    - role: yaourt
      tags: yaourt

    - role: pacman
      tags: pacman

    - role: lightdm
      tags: lightdm

    - role: xorg
      tags:
        - xorg
        - display

    - role: nvidia
      tags:
        - nvidia
        - display

    - role: intel_graphics
      tags:
        - intel_graphics
        - display

    - role: backlight
      tags: backlight

    - role: env-vars
      tags: env-vars

    - role: xdg-user-dirs
      tags: xdg-user-dirs

    - role: mimeapps
      tags: mimeapps

    - role: fish
      tags: fish

    - role: qtile
      tags: qtile

    - role: vim
      tags: vim

    - role: deepin-tools
      tags: deepin-tools

    - role: dunst
      tags: dunst

    - role: termite
      tags: termite

    - role: ranger
      tags: ranger

    - role: redshift
      tags: redshift

    - role: gtk3
      tags: gtk3

    - role: vimiv
      tags: vimiv

    - role: taskwarrior
      tags: taskwarrior

    - role: git
      tags: git
