---
- hosts: '{{ hostlist }}'
  become_user: root
  become: yes
  vars:
    hostlist: localhost

  roles:
    - { role: users, tags: users }
    - { role: sudoers, tags: sudoers }

- hosts: '{{ hostlist }}'
  become_user: '{{ username }}'
  become: yes
  vars:
    hostlist: localhost

  handlers:
    - name: Create initramfs image
      command: mkinitcpio -p linux
      become_user: root

    - name: Update pacman cache
      pacman:
        update_cache: yes
      become_user: root

  tasks:
    - name: "Clone this repo to {{ username }}'s home"
      git:
        repo: git@github.com:Sweenu/setup.git
        dest: '{{ repos_dir }}/setup'
        update: no
        accept_hostkey: yes

  roles:
    - { role: timezone, tags: timezone }
    - { role: locale, tags: locale }
    - { role: linux_console, tags: linux_console }
    - { role: hostname, tags: hostname }
    - { role: mkinitcpio, tags: mkinitcpio }
    - { role: grub, tags: grub }
    - { role: ansible, tags: ansible }
    - { role: ssh, tags: ssh }
    - { role: git, tags: git }
    - { role: pacman, tags: pacman }
    - { role: xdg-user-dirs, tags: xdg-user-dirs }
    - { role: pikaur, tags: pikaur }
    - { role: time, tags: time }
    - { role: networkmanager, tags: networkmanager }
    - { role: logind, tags: logind }
    - { role: nvidia, tags: [nvidia, display], when: has_nvidia_gpu }
    - { role: intel_graphics, tags: [intel_graphics, display], when: has_intel_gpu }
    - { role: ly, tags: ly }
    - { role: environment, tags: environment }
    - { role: fonts, tags: fonts }
    - { role: backlight, tags: backlight }
    - { role: bluetooth, tags: bluetooth }
    - { role: systemd-resolved, tags: systemd-resolved }
    # - { role: ufw, tags: ufw }
    - { role: openvpn, tags: openvpn }
    - { role: xkb, tags: xkb }
    - { role: pulseaudio, tags: pulseaudio }
    - { role: cups, tags: cups }
    - { role: tlp, tags: tlp, when: ansible_form_factor == 'Laptop'}
    - { role: python, tags: python }
    - { role: systemd, tags: systemd }
    - { role: gnome-keyring, tags: gnome-keyring }
    - { role: default_apps, tags: default_apps }
    - { role: neovim, tags: neovim }
    - { role: gtk3, tags: gtk3 }
    - { role: rclone, tags: rclone }
    - { role: fish, tags: fish }
    - { role: alacritty, tags: alacritty }
    - { role: spotify, tags: spotify }
    - { role: taskwarrior, tags: taskwarrior }
    - { role: docker, tags: docker }
    - { role: glances, tags: glances }
    - { role: rust, tags: rust }
    - { role: kdeconnect, tags: kdeconnect }
    - { role: redshift, tags: redshift }
    - { role: others, tags: others }
    # - { role: wireshark, tags: wireshark }
    # - { role: openlp, tags: openlp }

# post_tasks:
# - name: Enable ufw
#   ufw:
#     state: enabled
#   become_user: root
