---
- hosts: localhost
  become_user: root
  become: yes
  roles:
    - role: users
      tags: users

- hosts: localhost
  become_user: '{{ username }}'
  become: yes

  handlers:
    - name: Create initramfs image
      command: mkinitcpio -p linux
      become_user: root

  tasks:
    # TODO: make this task work during first setup and remove 'ignore_errors: yes'
    - name: "Clone this repo to {{ username }}'s home"
      git:
        repo: git@github.com:Sweenu/setup.git
        dest: '{{ user_dir }}/setup'
        update: no
      ignore_errors: yes

  roles:
    - role: timezone
      tags: timezone

    - role: locale
      tags: locale

    - role: linux_console
      tags: linux_console

    - role: hostname
      tags: hostname

    - role: mkinitcpio
      tags: mkinitcpio

    - role: grub
      tags: grub

    - role: ssh
      tags: ssh

    - role: git
      tags: git

    - role: pacman
      tags: pacman

    - role: yaourt
      tags: yaourt

    - role: sudoers
      tags: sudoers

    - role: time
      tags: time

    - role: networkmanager
      tags: networkmanager

    - role: ufw
      tags: ufw

    - role: logind
      tags: logind

    - role: xorg
      tags:
        - xorg
        - display

    - role: nvidia
      when: nvidia_gpu_present
      tags:
        - nvidia
        - display

    - role: intel_graphics
      when: intel_gpu_present
      tags:
        - intel_graphics
        - display

    - role: lightdm
      tags: lightdm

    - role: fonts
      tags: fonts

    - role: backlight
      tags: backlight

    - role: bluetooth
      tags: bluetooth

    - role: tunnelbear
      tags: tunnelbear

    - role: pulseaudio
      tags: pulseaudio

    - role: cups
      tags: cups

    - role: tlp
      tags: tlp
      when: ansible_form_factor == 'Laptop'

    - role: python
      tags: python

    - role: ansible
      tags: ansible

    - role: systemd
      tags: systemd

    - role: gnome-keyring
      tags: gnome-keyring

    - role: profile
      tags: profile

    - role: xdg-user-dirs
      tags: xdg-user-dirs

    - role: neovim
      tags: neovim

    - role: oni
      tags: oni

    - role: gtk3
      tags: gtk3

    - role: rclone
      tags: rclone

    - role: fish
      tags: fish

    - role: termite
      tags: termite

    - role: qtile
      tags: qtile

    - role: spotify
      tags: spotify

    - role: deepin-tools
      tags: deepin-tools

    - role: vimiv
      tags: vimiv

    - role: taskwarrior
      tags: taskwarrior

    - role: docker
      tags: docker

    - role: firefox
      tags: firefox

    - role: glances
      tags: glances

    - role: light-locker
      tags: light-locker

    - role: alsi
      tags: alsi

    # - role: lutris
    #   tags: lutris

    - role: latex
      tags: latex

    - role: rofi
      tags: rofi

    - role: openlp
      tags: openlp

    - role: compton
      tags:
        - compton
        - user_service

    - role: dunst
      tags:
        - dunst
        - user_service

    - role: clipster
      tags:
        -clipster
        - user_service

    - role: kdeconnect
      tags:
        - kdeconnect
        - user_service

    - role: redshift
      tags:
        - redshift
        - user_service

    - role: ranger
      tags: ranger

    - role: rust
      tags: rust

    - role: others
      tags: others
