---
- name: Create user directories for systemd
  file:
    path: '{{ config_home }}/systemd/user/{{ item }}'
    state: directory
    recurse: yes
  loop:
    - default.target.wants
    - timer.target.wants

- name: Configure systemd
  lineinfile:
    path: /etc/systemd/{{ item }}.conf
    regexp: '^#?DefaultLimitNOFILE='
    line: DefaultLimitNOFILE=1048576
  become_user: root
  loop:
    - user
    - system
