---
- name: Insall kanshi
  pacman:
    name: kanshi
  become_user: root

- name: Make sure kanshi config directory exists
  file:
    path: '{{ config_home }}/kanshi'
    state: directory

- name: Configure kanshi
  template:
    src: config.j2
    dest: '{{ config_home }}/kanshi/config'
