---
- name: Install BlueZ and BlueZ-utils
  pacman:
    name: '{{ item }}'
  loop:
    - bluez
    - bluez-utils
  become_user: root

- name: Make sure the btusb module is loaded
  modprobe:
    name: btusb
 
- name: Enable bluetooth service
  systemd:
    name: bluetooth
    enabled: yes
  become_user: root

- name: Install Broadcom specific firmware if needed
  aur:
    name: '{{ broadcom_card | lower }}-firmware'
  when: has_broadcom_card|bool
  ignore_errors: yes

- import_tasks: blueman.yml
