let g:pymode_python = 'python3'
let g:pymode_folding = 0
" let g:pymode_lint_ignore = 'E501,W'
let g:pymode_rope_goto_definition_bind = 'gtd'
let g:pymode_rope_rename_bind = '<Leader>cw'
let g:pymode_rope_autoimport_bind = '<Leader>i'
let g:pymode_rope_organize_imports_bind = '<Leader>i'
let g:pymode_rope_change_signature_bind = '<Leader>cs'
let g:pymode_syntax_print_as_function = 0
let g:pymode_options = 0
