---
- name: Install qtile
  yaourt:
    name: qtile-python3-git

- name: Install optional dependencies
  pacman:
    name: '{{ item }}'
  become_user: root
  loop:
    - alsa-utils
    - python-iwlib
    - python-setproctitle

- name: Install config dependencies
  pacman:
    name: python-dbus, python-parse, feh, pacman-contrib
  become_user: root

- name: Install the pynput module
  pip:
    name: pynput
  become_user: root

- name: Create qtile config directory
  file:
    path: '{{ config_home }}/qtile'
    state: directory

- name: Configure qtile
  template:
    src: '{{ item }}.py.j2'
    dest: '{{ config_home }}/qtile/{{ item }}.py'
  loop:
    - bars
    - config
    - keys
    - util
    - colors
    - widgets

- import_tasks: png-icons.yml
