---
- name: Make sure '{{ icon_dir }}' is present
  file:
    path: '{{ icon_dir }}'
    state: directory
    recurse: yes

- name: Find audio and battery icons
  find:
    paths: '{{ original_icon_dir }}'
    patterns: 'audio-*,battery-*'
  register: icons

- name: Convert the SVG icons to PNG
  shell: >
    rsvg-convert -w 1024 -h 1024 {{ item.path }} >
    {{ icon_dir }}/{{ (item.path | basename) | replace('-symbolic.svg', '.png') }}
  args:
    creates: '{{ icon_dir }}/{{ (item.path | basename) | replace("-symbolic.svg", ".png") }}'
  loop: '{{ icons.files }}'
