---
- name: Install OpenLP
  yaourt:
    name: openlp

- name: Install optional dependencies
  pacman:
    name: '{{ item }}'
  become: true
  loop:
    - libreoffice-fresh
    - vlc
    - mupdf

- name: Sync backup if there are any differences
  command: rclone copy gdrive:openlp {{ data_home }}/openlp
  args:
    creates: '{{ data_home }}/openlp'
