---
- name: Install OpenLP
  yaourt:
    name: openlp

- name: Install optional dependencies
  pacman:
    name: '{{ item }}'
  become_user: root
  loop:
    - libreoffice-fresh
    - vlc
    - mupdf

- name: Create config directory
  file:
    path: '{{ config_dir }}/OpenLP'
    state: directory

- name: Configure OpenLP
  template:
    src: 'OpenLP.conf.j2'
    dest: '{{ config_dir }}/OpenLP/OpenLP.conf'

# - name: Import backup
#   command: rclone copy gdrive:openlp {{ data_home }}/openlp
#   args:
#     creates: '{{ data_home }}/openlp'
