---
- name: Configure NextCloud
  ini_file:
    path: '{{ config_home }}/rclone/rclone.conf'
    section: '{{ nextcloud.name }}'
    option: '{{ item.option }}'
    value: '{{ item.value }}'
  loop:
    - { option: type, value: webdav }
    - { option: url, value: '{{ nextcloud.url }}' }
    - { option: vendor, value: nextcloud }
    - { option: user, value: '{{ nextcloud.user }}' }
    - { option: pass, value: '{{ nextcloud.pass }}' }
