---
- name: Install task
  pacman:
    name: task
  become_user: root

- name: Configure dunst
  template:
    src: taskrc.j2
    dest: '{{ user_dir }}/.taskrc'

- name: Configure Inthe.am
  copy:
    src: ./
    dest: '{{ data_home }}/task/'
    mode: 0600
