---
- name: Install ranger
  pacman:
    name: ranger
  become: true

- name: Create ranger config directory
  file:
    path: '{{ defaults.config_home }}/ranger'
    state: directory

- name: Configure ranger
  template:
    src: rc.conf.j2
    dest: '{{ defaults.config_home }}/ranger/rc.conf'
