---
- name: Install bumblebee
  pacman:
    name: bumblebee

- name: Install primus
  pacman:
    name: primus

- name: Install bbswitch
  pacman:
    name: bbswitch

- name: Create bumblebee group
  group:
    name: bumblebee

- name: Add user '{{ username }}' to bumblebee group
  user:
    name: '{{ username }}'
    groups: bumblebee
    append: yes

- name: Configure bumblebee
  ini_file:
    path: /etc/bumblebee/bumblebee.conf
    section: '{{ item.section }}'
    option: '{{ item.option}}'
    value: '{{ item.value }}'
    no_extra_spaces: yes
  loop:
    - { section: 'bumblebeed',    option: 'Driver',   value: 'nvidia' }
    - { section: 'optirun',       option: 'Bridge',   value: 'primus' }
    - { section: 'driver-nvidia', option: 'PMMethod', value: 'bbswitch' }

- name: Enable the bumblebeed service
  systemd:
    name: bumblebeed
    enabled: yes
