---
- name: Install Bumblebee and optional dependencies
  pacman:
    name: '{{ item }}'
  become_user: root
  loop:
    - bumblebee
    - primus
    - bbswitch
    - lib32-virtualgl
    - lib32-primus
    - lib32-nvidia-utils

- name: Create bumblebee group
  group:
    name: bumblebee
  become_user: root

- name: Add user '{{ username }}' to bumblebee group
  user:
    name: '{{ username }}'
    groups: bumblebee
    append: yes
  become_user: root

- name: Configure bumblebee
  ini_file:
    path: /etc/bumblebee/bumblebee.conf
    section: '{{ item.section }}'
    option: '{{ item.option}}'
    value: '{{ item.value }}'
    no_extra_spaces: yes
  loop:
    - { section: 'bumblebeed',    option: 'Driver',   value: 'nvidia' }
    - { section: 'optirun',       option: 'Bridge',   value: 'primus' }
    - { section: 'driver-nvidia', option: 'PMMethod', value: 'bbswitch' }
  become_user: root

- name: Enable the bumblebeed service
  systemd:
    name: bumblebeed
    enabled: yes
  become_user: root
