---
- name: Enable systemd-resolved
  systemd:
    name: systemd-resolved
    enabled: yes
  become_user: root

- name: Symlink /etc/resolv.conf to /run/systemd/resolve/stub-resolv.conf
  file:
    state: link
    src: /run/systemd/resolve/stub-resolv.conf
    dest: /etc/resolv.conf
  become_user: root

- name: Disable MulticastDNS as it is taken care by Avahi
  ini_file:
    path: /etc/systemd/resolved.conf
    section: Resolve
    option: MulticastDNS
    value: no
  become_user: root
