---
- name: Create mapping '{{ mapping_name }}'
  expect:
    command: cryptsetup open /dev/{{ root_partition }} {{ mapping_name }}
    responses:
      '.*passphrase.*': '{{ encryption_passphrase }}'
    creates: /dev/mapper/{{ mapping_name }}
