---
- name: Create mapping 'crypttemp'
  expect:
    command: "cryptsetup{{ ' --allow-discards --persistent' if activate_trim else '' }}
             open /dev/{{ root_partition }} crypttemp"
    responses:
      '.*passphrase.*': '{{ encryption_passphrase }}'
    creates: /dev/mapper/crypttemp
  changed_when: false
