---
# Cups can only be used with avahi: https://github.com/apple/cups/issues/5452
- name: Install Avahi and it's optional dependencies
  pacman:
    name:
      - avahi
      - nss-mdns
  become_user: root

- name: Enable avahi-daemon
  systemd:
    name: avahi-daemon.service
    enabled: yes
  become_user: root

- name: Configure hostname resolution
  replace:
    path: /etc/nsswitch.conf
    regexp: '^(hosts: .*) (resolve .*)'
    replace: '\1 mdns_minimal [NOTFOUND=return] \2'
  become_user: root
