---
- name: Install Avahi and it's optional dependencies
  pacman:
    name: '{{ item }}'
  become_user: root
  loop:
    - avahi
    - nss-mdns

- name: Configure hostname resolution
  replace:
    path: /etc/nsswitch.conf
    # TODO: make a better regex
    regexp: '^(hosts: .* myhostname) (resolve .* dns)'
    replace: '\1 mdns_minimal [NOTFOUND=return] \2'
  become_user: root
