---
- name: Install termite
  pacman:
    name: termite
  become_user: root

- name: Create termite config directory
  file:
    path: '{{ config_home }}/termite'
    state: directory

- name: Configure termite
  template:
    src: config.j2
    dest: '{{ config_home }}/termite/config'
