---
- name: Install glances
  pacman:
    name: glances
  become: true

- name: Install optional dependencies
  pacman:
    name: '{{ item }}'
  become: true
  loop:
    - hddtemp
    - python-docker
    - python-matplotlib
    - python-netifaces
    - python-zeroconf
