---
- name: Install glances
  pacman:
    name: glances
  become_user: root

- name: Install optional dependencies
  pacman:
    name: '{{ item }}'
  become_user: root
  loop:
    - hddtemp
    - python-docker
    - python-matplotlib
    - python-netifaces
    - python-zeroconf
