---
- name: Install glances
  pacman:
    name: glances
  become_user: root

- name: Install optional dependencies
  pacman:
    name:
      - hddtemp
      - python-docker
      - python-matplotlib
      - python-netifaces
      - python-zeroconf
  become_user: root
