---
- name: Install Pikaur
  yaourt:
    name: pikaur

- name: Configure Pikaur
  ini_file:
    path: '{{ config_home }}/pikaur.conf'
    section: '{{ item.section }}'
    option: '{{ item.option }}'
    value: '{{ item.value }}'
  loop:
    - { section: 'sync', option: 'alwaysshowpkgorigin', value: 'yes' } 
    - { section: 'build', option: 'noedit', value: 'yes' } 
    - { section: 'build', option: 'nodiff', value: 'yes' } 
    - { section: 'ui', option: 'requireenterconfirm', value: 'no' } 
