---
- name: Install pikaur
  aur:
    name: pikaur

- name: Configure Pikaur
  ini_file:
    path: '{{ config_home }}/pikaur.conf'
    section: '{{ item.section }}'
    option: '{{ item.option }}'
    value: '{{ item.value }}'
  loop:
    - { section: 'sync', option: 'alwaysshowpkgorigin', value: 'yes' }
    - { section: 'sync', option: 'showdownloadsize', value: 'yes' }
    - { section: 'build', option: 'donteditbydefault', value: 'yes' }
    - { section: 'build', option: 'nodiff', value: 'yes' }
    - { section: 'ui', option: 'requireenterconfirm', value: 'no' }
