---
- name: Clone spotifywm to '{{ repos_dir }}'
  git:
    repo: https://github.com/dasJ/spotifywm
    dest: '{{ repos_dir }}/spotifywm'

- name: Build spotifywm
  make:
    chdir: '{{ repos_dir }}/spotifywm'

- name: Install the library
  copy:
    src: '{{ repos_dir }}/spotifywm/spotifywm.so'
    dest: /usr/share/spotify/
  become_user: root

- name: Install custom spotify executable
  copy:
    src: spotify.sh
    dest: /usr/bin/spotify
    mode: 0755
    owner: root
    group: root
  become_user: root

- name: Create 'hooks' directory
  file:
    path: /etc/pacman.d/hooks
    state: directory
  become_user: root

- name: Install custom pacman hook for spotify
  template:
    src: spotifywm.hook.j2
    dest: /etc/pacman.d/hooks/spotifywm.hook
  become_user: root
