---
- name: Unmount /mnt/boot
  mount:
    path: /mnt/boot
    state: unmounted

- name: Unmount /mnt
  mount:
    path: /mnt
    state: unmounted

- import_role:
    name: remove_mapping
  when: encrypted_root
