---
- name: Unmount /mnt/boot
  mount:
    path: /mnt/boot
    state: unmounted
  changed_when: false

- name: Unmount /mnt
  mount:
    path: /mnt
    state: unmounted
  changed_when: false

- import_role:
    name: remove_mapping
  when: encrypted_root
