---
- name: Install UFW
  pacman:
    name: ufw

- name: Enable UFW and set default policy to 'deny'
  ufw:
    state: enabled
    policy: deny

- name: Enable service
  systemd:
    name: ufw
    enabled: yes
