---
- name: Install UFW
  pacman:
    name: ufw
  become_user: root

- name: Enable UFW and set default policy to 'deny'
  ufw:
    policy: deny
  become_user: root

- name:
  ufw:
    rule: allow
    to_ip: '{{ item }}'
    direction: out
  become_user: root
  loop:
    - 192.168.0.0/16
    - 172.16.0.0/12
    - 10.0.0.0/8
