---
- name: Install git
  pacman:
    name: git
  become_user: root

- name: Create git config directory
  file:
    path: '{{ config_home }}/git'
    state: directory

- name: Configure git
  template:
    src: config.j2
    dest: '{{ config_home }}/git/config'

- name: Configure global gitignore
  template:
    src: gitignore.j2
    dest: '{{ config_home }}/git/gitignore'

- name: Install libsecret to use gnome-keyring
  pacman:
    name: libsecret
  become_user: root

- name: Add Github to known_hosts
  known_hosts:
    name: github.com
    key: '{{ lookup("pipe", "ssh-keyscan -t rsa github.com") }}'
