---
- name: Install git
  pacman:
    name: git
  become: true

- name: Create git config directory
  file:
    path: '{{ defaults.config_home }}/git'
    state: directory

- name: Configure git
  template:
    src: config.j2
    dest: '{{ defaults.config_home }}/git/config'

- name: Configure global gitignore
  template:
    src: gitignore.j2
    dest: '{{ defaults.config_home }}/git/gitignore'

- name: Install libsecret to use gnome-keyring
  pacman:
    name: libsecret
  become: true
