---
- name: Set systemd timers to pause and resume notifications during church service
  copy:
    src: dunst-{{ item }}
    dest: '{{ config_home }}/systemd/user/'
  loop:
    - pause.timer
    - pause.service
    - resume.timer
    - resume.service

- name: Enable those timers
  file:
    src: '{{ config_home }}/systemd/user/dunst-{{ item }}.timer'
    dest: '{{ config_home }}/systemd/user/timers.target.wants/dunst-{{ item }}.timer'
    state: link
  loop:
    - pause
    - resume
