---
- name: Install dunst
  pacman:
    name: dunst
  become: true

- name: Create dunst config directory
  file:
    path: '{{ defaults.config_home }}/dunst'
    state: directory

- name: Configure dunst
  template:
    src: dunstrc.j2
    dest: '{{ defaults.config_home }}/dunst/dunstrc'

- include_tasks: autopause.yml
