---
- name: Install dunst
  pacman:
    name: dunst
  become_user: root

- name: Create dunst config directory
  file:
    path: '{{ config_home }}/dunst'
    state: directory

- name: Configure dunst
  template:
    src: dunstrc.j2
    dest: '{{ config_home }}/dunst/dunstrc'

- import_tasks: autopause.yml
