---
- name: install dunst
  pacman:
    name: dunst
    state: present
  become: true

- name: create dunst config directory
  file:
    path: '{{ defaults.config_home }}/dunst'
    state: directory

- name: configure dunst
  template:
    src: dunstrc.j2
    dest: '{{ defaults.config_home }}/dunst/dunstrc'

- name: Set systemd timers to pause and resume notifications during church service
  copy:
    src: dunst-{{ item }}
    dest: '{{ defaults.config_home }}/systemd/user/'
  loop:
    - pause.timer
    - pause.service
    - resume.timer
    - resume.service

- name: Enable and start those timers
  systemd:
    name: dunst-{{ item }}.timer
    daemon-reload: yes
    user: yes
    enabled: yes
    state: started
  loop:
    - pause
    - resume
