---
- name: Install reflector
  pacman:
    name: reflector

- name: Generate mirrorlist with reflector
  command: reflector --sort score -n 10 --save /etc/pacman.d/mirrorlist
  args:
    creates: /etc/pacman.d/mirrorlist
