---
- name: Set root's password
  user:
    name: root
    password: '{{ root_password | password_hash("sha512", root_salt) }}'
  become: true

- name: Create main user
  user:
    name: '{{ username }}'
    password: '{{ user_password | password_hash("sha512") }}'
    update_password: on_create
    group: sweenu
    groups: wheel
    shell: /usr/bin/fish
    append: yes
  become: true
