---
- name: Set root's password
  user:
    name: root
    password: '{{ root_password | password_hash("sha512", root_salt) }}'

- name: Create user '{{ username }}'
  user:
    name: '{{ username }}'
    password: '{{ user_password | password_hash("sha512") }}'
    update_password: on_create
    shell: /usr/bin/fish
    group: sweenu
    groups: [ wheel, adm ]
    append: yes
