---
- name: Change root's password
  user:
    name: root
    password: '{{ root_password | password_hash("sha512") }}'
    update_password: on_create
    create_home: no
  become: true

- name: Create main user
  user:
    name: '{{ username }}'
    password: '{{ user_password | password_hash("sha512") }}'
    update_password: on_create
    group: sweenu
    groups: wheel
    shell: /usr/bin/fish #xonsh
    append: yes
  become: true
