---
- name: Install every other programs
  pacman:
    name: '{{ item }}'
  become_user: root
  loop:
    - archiso
    - bat
    - bind-tools
    - entr
    - fd
    - fwupd
    - fzf
    - htop
    - httpie
    - imv
    - lshw
    - man-db
    - man-pages
    - mlocate
    - ncdu
    - neofetch
    - net-tools
    - nmap
    - powertop
    - ripgrep
    - speedtest-cli
    - telegram-desktop
    - tldr
    - traceroute
    - trash-cli
    - tree
    - unzip
    - wget
    - whois
    - youtube-dl
    - zip

- name: Install every other programs in AUR
  aur:
    name: '{{ item }}'
  loop:
    - bitwarden-cli
    - brave-bin
    - wf-recorder-git
    - wev-git
    - wdisplays-git
