---
- name: Install TLP
  pacman:
    name: tlp
  become_user: root

- name: Install optional dependencies
  pacman:
    name: x86_energy_perf_policy
  become_user: root

- name: Configure TLP
  lineinfile:
    path: /etc/default/tlp
    regexp: '^{{ item.option }}='
    line: '{{ item.option }}={{ item.value }}'
  loop:
    - { option: 'CPU_HWP_ON_AC', value: 'performance' }
    - { option: 'CPU_HWP_ON_BAT', value: 'balance_power' }
    - { option: 'DEVICES_TO_ENABLE_ON_AC', value: '"bluetooth"' }
    - { option: 'DEVICES_TO_DISABLE_ON_BAT_NOT_IN_USE', value: '"bluetooth"' }
    - { option: 'DEVICES_TO_DISABLE_ON_STARTUP', value: '"bluetooth"' }
  become_user: root

- name: Check if bumblebee is in use
  command: systemctl is-enabled bumblebeed
  changed_when: false
  register: use_bumblebee
  become_user: root

- import_tasks: gpu_blacklist.yml
  when: use_bumblebee is succeeded

- name: Enable the 'tlp' service
  systemd:
    name: tlp
    enabled: yes
  become_user: root

- name: Enable the 'tlp-sleep' service
  systemd:
    name: tlp
    enabled: yes
  become_user: root

- name: Mask 'systemd-rfkill' service and socket
  systemd:
    name: systemd-rfkill.{{ item }}
    masked: yes
  loop:
    - service
    - socket
  become_user: root
