---
- name: Install Ansible
  pacman:
    name: ansible
  become_user: root

- name: Install optional dependencies
  pacman:
    name:
      - python-jmespath
      - python-pexpect
      - rsync
  become_user: root

- name: Configure Ansible
  template:
    src: ansible.cfg.j2
    dest: '{{ user_dir }}/.ansible.cfg'
