---
- name: Install Ansible
  pip:
    name: ansible
  become: true

- name: Configure Ansible
  template:
    src: ansible.cfg.j2
    dest: '{{ ansible_user_dir }}/.ansible.cfg'

- name: "Clone this repo to {{ ansible_user_id }}'s home"
  git:
    repo: git@github.com:Sweenu/setup.git
    dest: '{{ ansible_user_dir }}/setup'
    update: no

- name: Install ansible-lint
  pip:
    name: ansible-lint
  become: true
