---
- name: Make sure Ansible isn't installed with pacman
  pacman:
    name: ansible
    state: absent
  become: true

- name: Install Ansible dependencies with pacman
  pacman:
    name: python-jinja python-pyaml python-paramiko python-cryptography python-setuptools
  become: true

- name: Install Ansible
  pip:
    name: ansible
  become: true

- name: Configure Ansible
  template:
    src: ansible.cfg.j2
    dest: '{{ user_dir }}/.ansible.cfg'

- name: Install ansible-lint
  pip:
    name: ansible-lint
  become: true
