---
- name: Install accountsservice
  pacman:
    name: accountsservice
  become_user: root

- name: Copy picture from NextCloud
  command: rclone copy ncloud:Pictures/{{ profile_icon_name }} {{ profile_icon_path }}
  args:
    creates: '{{ profile_icon_path }}'

- name: Symlink profile icon
  file:
    src: '{{ profile_icon_path }}'
    dest: '{{ user_dir }}/.face'
    state: link
