---
- set_fact:
    service_file: kdeconnect-indicator.service

- name: Create kdeconnect-indicator service file
  template:
    src: '{{ service_file }}.j2
    dest: '{{ config_home }}/systemd/user/{{ service_file }}'

- name: Enable indicator-kdeconnect service
  file:
    src: '{{ config_home }}/systemd/user/{{ service_file }}'
    dest: '{{ config_home }}/systemd/user/default.target.wants/{{ service_file }}'
    state: link
