---
- name: Install lightdm
  pacman:
    name: lightdm
  become: true

- include_tasks: accountsservice.yml

- include_tasks: greeter.yml

- name: Configure lightdm
  template:
    src: lightdm.conf.j2
    dest: /etc/lightdm/lightdm.conf
  become: true

- name: Enable lightdm service
  systemd:
    name: lightdm-plymouth
    enabled: yes
  become: true

- include_tasks: plymouth.yml
