---
- name: Install lightdm
  pacman:
    name: lightdm
  become: true

- name: Configure lightdm
  template:
    src: lightdm.conf.j2
    dest: /etc/lightdm/lightdm.conf
  become: true

- name: Enable and start lightdm service
  systemd:
    name: lightdm
    daemon-reload: yes
    enabled: yes
    state: started
  become: true

- include_tasks: accountsservice.yml
- include_tasks: greeter.yml
