---
- block:
    - name: Set the timezone
      timezone:
        name: '{{ timezone }}'
  rescue:
    - name: Set the timezone manually
      file:
        src: /usr/share/zoneinfo/{{ timezone }}
        path: /etc/localtime
        state: link
  become_user: root

# - name: Synchromize hwclock with sysclock
#   command: hwclock --systohc --verbose
#   args:
#     creates: /etc/adjtime
#   become_user: root
