---
- block:
    - name: Set the timezone
      timezone:
        name: '{{ timezone }}'
  rescue:
    - name: Set the timezone manually
      file:
        src: /usr/share/zoneinfo/{{ timezone }}
        path: /etc/localtime
        state: link

- name: Check if adjtime file exists
  stat:
    path: /etc/adjtime
  register: adjtime

- name: Synchromize hwclock with sysclock
  command: hwclock --systohc
  when: not adjtime.stat.exists
  become: true
