---
- name: Format LUKS device
  command: cryptsetup -y luksFormat --type luks2 /dev/{{ disk }}{{ root_partition }}
  changed_when: false

- name: Open device as mapping '{{ mapping_name }}'
  command: cryptsetup open /dev/{{ disk }}{{ root_partition }} {{ mapping_name }}
  changed_when: false

- name: Set fact for mapping to root partition
  set_fact:
    encrypted_mapping: '{{ mapping_name }}'
