---
- name: Install Docker
  pacman:
    name: docker
  become_user: root

- name: Add user '{{ username }}' to docker group
  user:
    name: '{{ username }}'
    groups: docker
    append: yes
  become_user: root

- name: Install docker-compose
  pacman:
    name: docker-compose
  become_user: root
