---
- name: Install Docker and docker-compose
  pacman:
    name:
      - docker
      - docker-compose
  become_user: root

- name: Add user '{{ username }}' to docker group
  user:
    name: '{{ username }}'
    groups: docker
    append: yes
  become_user: root
