---
- name: Install xdg-user-dirs
  pacman:
    name: xdg-user-dirs
  become_user: root

- name: Configure user-dirs
  template:
    src: user-dirs.dirs.j2
    dest: '{{ config_home }}/user-dirs.dirs'
