---
- name: Install '{{ gtk_theme }}' theme
  pacman:
    name: '{{ gtk_theme | lower }}-gtk-theme'
  become: true

- name: Install '{{ icon_theme }}' icon theme
  pacman:
    name: '{{ icon_theme | lower }}-icon-theme'
  become: true

- name: Create gtk3 config directory
  file:
    path: '{{ config_home }}/gtk-3.0'
    state: directory

- name: Configure gtk3
  ini_file:
    path: '{{ config_home }}/gtk-3.0/settings.ini'
    section: Settings
    option: '{{ item.option }}'
    value: '{{ item.value }}'
  loop:
    - { option: gtk-theme-name, value: '{{ gtk_theme_variant }}' }
    - { option: gtk-application-prefer-dark-theme,
        value: "{{ dark_theme | ternary('true', 'false') }}" }
    - { option: gtk-icon-theme-name, value: '{{ icon_theme_variant }}' }
