---
- name: Install NetworkManager
  pacman:
    name: networkmanager
  become_user: root

- name: Enable NetworkManager
  systemd:
    name: NetworkManager
    enabled: yes
  become_user: root

# - name: Decrypt and copy connections
#   unarchive:
#     src: connections.tar.gz
#     dest: /etc/NetworkManager/system-connections/
#     mode: 0600
#   become_user: root

- name: Install nm-applet
  pacman:
    name: network-manager-applet
  become_user: root
