---
- name: Install NetworkManager
  pacman:
    name: networkmanager
  become: true

- name: Enable and start NetworkManager
  systemd:
    name: NetworkManager
    enabled: yes
    state: started
  become: true
