---
- name: Install NetworkManager
  pacman:
    name: networkmanager

- name: Decrypt and copy connections
  copy:
    src: ./
    dest: /etc/NetworkManager/system-connections/
    mode: 0600

- name: Enable NetworkManager
  systemd:
    name: NetworkManager
    enabled: yes

- name: Install nm-applet
  pacman:
    name: network-manager-applet
