---
- name: Install GRUB and efibootmgr
  pacman:
    name:
      - grub
      - efibootmgr
  become_user: root

- name: Install GRUB onto the boot partition
  command: >
    grub-install
    --target=x86_64-efi
    --bootloader-id={{ bootloader_identifier }}
    --efi-directory=/boot
    {{ " --removable" if removable_drive else "" }}
  args:
    creates: /boot/EFI/{{ bootloader_identifier + '/grubx64.efi' if not removable_drive 
                                                                 else 'BOOT/BOOTX64.EFI' }}
  become_user: root

- name: Configure GRUB
  template:
    src: grub.j2
    dest: /etc/default/grub
  notify: Update GRUB
  become_user: root
