---
- name: Install GRUB and efibootmgr
  pacman:
    name: grub efibootmgr

- name: Install GRUB onto the boot partition
  command: 'grub-install --target=x86_64-efi --efi-directory=/boot --bootloader-id={{ bootloader_identifier }}'
  args:
    creates: /boot/EFI/{{ bootloader_identifier }}/grubx64.efi

- name: Configure GRUB
  template:
    src: grub.j2
    dest: /etc/default/grub
  notify: Update GRUB
