---
- name: Install pgcli
  aur:
    name: pgcli

- name: Create pgcli config directory
  file:
    path: '{{ config_home }}/pgcli'
    state: directory

- name: Configure pgcli
  ini_file:
    path: '{{ config_home }}/pgcli/config'
    section: main
    option: '{{ item.key }}'
    value: '{{ item.value }}'
  with_dict:
    multi_line: 'True'
    generate_aliases: 'True'
    vi: 'True'
    less_chatty: 'True'
    row_limit: 350
    syntax_style: paraiso-dark

- name: Configure named queries
  ini_file:
    path: '{{ config_home }}/pgcli/config'
    section: named queries
    option: '{{ item.key }}'
    value: '{{ item.value }}'
  with_dict:
    table_sizes: |
      '''SELECT nspname, relname, pg_size_pretty(pg_relation_size(c.oid)) as "size"
      FROM pg_class c LEFT JOIN pg_namespace n ON n.oid = c.relnamespace
      WHERE nspname NOT IN ('pg_catalog','information_schema')
      ORDER BY pg_relation_size(c.oid)
      DESC LIMIT 30'''
      list_triggers = '''SELECT tgname FROM pg_trigger
      WHERE tgrelid = '$1'::regclass'''
    list_locks: |
        '''SELECT pid, state, usename, query, query_start
        FROM pg_stat_activity
        WHERE pid IN (
            SELECT pid FROM pg_locks l
            JOIN pg_class t ON l.relation = t.oid AND t.relkind = 'r'
            WHERE t.relname = '$1'
        )'''
