---
- name: Create necessary directories for vim-plug
  file:
    path: '{{ defaults.data_home }}/nvim/{{ item }}'
    state: directory
  loop:
    - site
    - site/autoload

- name: Install 'vim-plug' plugin manager
  get_url:
    url: https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
    dest: '{{ defaults.data_home }}/nvim/site/autoload/'
  notify: Install plugins
