---
- name: Install acpilight
  yaourt:
    name: acpilight

- name: Configure a udev rule for users in 'video' group to use acpilight
  template:
    src: 90-backlight.rules.j2
    dest: /etc/udev/rules.d/90-backlight.rules
  become: true

- name: Add user '{{ ansible_user_id }}' to 'video' group
  user:
    name: '{{ ansible_user_id }}'
    groups: video
    append: yes
  become: true
