---
- name: Install OpenVPN
  pacman:
    name: openvpn
  become_user: root

- name: Install NetworkManager OpenVPN
  pacman:
    name: networkmanager-openvpn
  become_user: root

- name: Install optional dependencies
  pacman:
    name: easy-rsa
  become_user: root

- import_tasks: firewall.yml

- import_tasks: nordvpn.yml
