---
- block:
    - name: Check if custom package is installed
      command: pacman -Qi nordvpn-config
      changed_when: false
  rescue:
    - name: Install custom package if not already installed
      block:
        - name: Download custom package
          get_url:
            url: https://github.com/Sweenu/nordvpn-config/releases/download/1.0/nordvpn-config-1.0-1-x86_64.pkg.tar.xz
            dest: /tmp/

        - name: Install package
          command: pacman -U --noconfirm /tmp/nordvpn-config-1.0-1-x86_64.pkg.tar.xz
          become_user: root

- name: Copy credential file
  template:
    src: login.key.j2
    dest: /etc/openvpn/client/login.key
    mode: 0600
  become_user: root
