---
- import_tasks: wipe_disk.yml
  when: wipe_disk

- import_tasks: partition.yml

- name: Encrypt disk with dm-crypt + LUKS
  block:
    - name: Format LUKS device
      expect:
        command: cryptsetup luksFormat --type luks2 /dev/{{ disk }}{{ root_partition }}
        responses:
          '.*Are you sure?.*': 'YES'
          '.*passphrase.*': {{ encryption_passphrase }}
      changed_when: false

    - name: Open device as mapping '{{ mapping_name }}'
      command: cryptsetup open /dev/{{ disk }}{{ root_partition }} {{ mapping_name }}
      changed_when: false
  when: use_encryption

- import_tasks: format.yml

- name: Install Arch
  block:
    - import_tasks: mount.yml

    - name: Pacstrap
      command: 'pacstrap /mnt base base-devel ansible grub efibootmgr networkmanager
               {{ shell }} {{ "intel-ucode" if is_intel_cpu else "" }}
               {{ "btrfs-progs" if fstype == "btrfs" else "" }}'
      changed_when: false

    - name: Generate fstab
      shell: genfstab -U /mnt > /mnt/etc/fstab
      args:
        creates: /mnt/etc/fstab

    - name: Copy this repo, from the usb key to the mounted disk
      copy:
        src: /root/setup
        dest: /mnt/root/

    - name: Chroot and do necessary install
      command: 'arch-chroot /mnt ansible-playbook /root/setup/site.yml
               --tags install --vault-id @prompt'
  always:
    - name: Unmount /mnt/boot
      mount:
        path: /mnt/boot
        state: unmounted

    - name: Unmount /mnt
      mount:
        path: /mnt
        state: unmounted
