---
- block:
    - include_role:
        name: create_mapping
      when: encrypted_root

    - include_role:
        name: mount

    - name: Pacstrap
      command: 'pacstrap /mnt base base-devel ansible grub efibootmgr networkmanager
               {{ shell }} {{ "btrfs-progs" if fstype == "btrfs" else "" }}'
      args:
        creates: /mnt/dev

    - name: Generate fstab
      shell: genfstab -U /mnt > /mnt/etc/fstab
      args:
        creates: /mnt/etc/fstab

    - name: Copy this repo, to the mounted disk
      copy:
        src: '{{ playbook_dir }}'
        dest: /mnt/root/

    - name: Chroot and do necessary install
      expect:
        command: 'arch-chroot /mnt ansible-playbook --vault-id @prompt /root/setup/site.yml'
        responses:
          '.*password.*': vault_passwd

  always:
    - include_role:
        name: unmount

    - include_role:
        name: remove_mapping
