---
- block:
    - include_role:
        name: mount

    - name: Pacstrap
      command: pacstrap /mnt {{ item.pkg }}
      args:
        creates: /mnt{{ item.file }}
      loop:
        - { pkg: base, file: /usr/bin/bash }
        - { pkg: base-devel, file: /usr/bin/sudo }
        - { pkg: btrfs-progs, file: /usr/bin/btrfs }

    - name: Generate fstab
      lineinfile:
        path: /mnt/etc/fstab
        line: '{{ item }}'
      loop: '{{ q("lines", "genfstab -U /mnt") }}'

  rescue:
    - include_role:
        name: unmount
