---
- block:
    - import_role: create_mapping
      when: encrypted_root

    - import_role: mount

    - name: Pacstrap
      command: 'pacstrap /mnt base base-devel ansible grub efibootmgr networkmanager
               {{ shell }} {{ "intel-ucode" if is_intel_cpu else "" }}
               {{ "btrfs-progs" if fstype == "btrfs" else "" }}'
      args:
        creates: /mnt/dev

    - name: Generate fstab
      shell: genfstab -U /mnt > /mnt/etc/fstab
      args:
        creates: /mnt/etc/fstab

    - name: Copy this repo, from the usb key to the mounted disk
      copy:
        src: /root/setup
        dest: /mnt/root/

    - name: Chroot and do necessary install
      command: 'arch-chroot /mnt ansible-playbook /root/setup/site.yml
               --tags install --vault-id @prompt'
  always:
    - import_role: unmount

    - import_role: remove_mapping
