---
- block:
    - import_role:
        name: mount

    - name: Pacstrap
      command: pacstrap /mnt base linux linux-firmware base-devel git python

    - name: Generate fstab
      lineinfile:
        path: /mnt/etc/fstab
        line: '{{ item }}'
      loop: '{{ q("lines", "genfstab -U /mnt") }}'

  rescue:
    - import_role:
        name: unmount
