---
- block:
    - include_role:
        name: mount

    - name: Pacstrap
      command: pacstrap /mnt {{ item.pkg }}
      args:
        creates: /mnt{{ item.file }}
      loop:
        - { pkg: base, file: /usr/bin/bash }
        - { pkg: base-devel, file: /usr/bin/sudo }

    - name: Generate fstab
      lineinfile:
        path: /mnt/etc/fstab
        line: '{{ item }}'
      loop: '{{ q("lines", "genfstab -U /mnt") }}'

    - name: Pull and run the playbook
      expect:
        command: 'arch-chroot /mnt ansible-pull -U https://github.com/Sweenu/setup
                 site.yml --vault-id @prompt -e disk={{ disk }}'
        responses:
          '.*password.*': '{{ vault_password }}'
        timeout: null

  always:
    - include_role:
        name: unmount
