---
- block: 
  name: Format boot partition with default number of sector per cluster
  filesystem:
    dev: /dev/{{ boot_partition }}
    fstype: vfat

  rescue:
  name: Format boot partition with one sector per cluster
  filesystem:
    dev: /dev/{{ boot_partition }}
    fstype: vfat
    opts: -s 1

- block:
    - include_role:
        name: create_mapping
      when: encrypted_root

    - name: Format root partition
      filesystem:
        dev: '/dev/{{ "mapper/" + mapping_name if encrypted_root 
                                               else root_partition }}'
        fstype: '{{ fstype }}'

  always:
    - include_role:
        name: remove_mapping
