---
- name: Format boot partition
  filesystem:
    dev: /dev/{{ boot_partition }}
    fstype: vfat

- block:
    - include_role:
        name: create_mapping
      when: encrypted_root

    - name: Format root partition
      filesystem:
        dev: /dev/{{ "mapper/" + mapping_name if encrypted_root else root_partition }}
        fstype: '{{ fstype }}'

  always:
    - include_role:
        name: remove_mapping
